# Generated by Django 5.2.8 on 2025-12-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='授業名')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('end_time', models.DateTimeField(verbose_name='終了日時')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='定員')),
                ('reservation_start_time', models.DateTimeField(verbose_name='予約開始時刻')),
            ],
            options={
                'verbose_name': '授業枠',
                'verbose_name_plural': '授業枠',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='連絡先電話番号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='保護者アカウント')),
            ],
            options={
                'verbose_name': '家族/保護者',
                'verbose_name_plural': '家族/保護者',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='生徒氏名')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.family', verbose_name='保護者')),
            ],
            options={
                'verbose_name': '生徒',
                'verbose_name_plural': '生徒',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='予約日時')),
                ('lesson_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.lessonslot', verbose_name='授業枠')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.student', verbose_name='予約生徒')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'unique_together': {('lesson_slot', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitlisted_at', models.DateTimeField(auto_now_add=True, verbose_name='補欠登録日時')),
                ('lesson_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.lessonslot', verbose_name='授業枠')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.student', verbose_name='補欠生徒')),
            ],
            options={
                'verbose_name': '補欠',
                'verbose_name_plural': '補欠',
                'ordering': ['waitlisted_at'],
                'unique_together': {('lesson_slot', 'student')},
            },
        ),
    ]
