# Generated by Django 5.2.15 on 2026-07-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('students', models.ManyToManyField(blank=True, related_name='groups', to='booking.student', verbose_name='生徒')),
            ],
            options={
                'verbose_name': '生徒グループ',
                'verbose_name_plural': '生徒グループ',
                'ordering': ['name'],
            },
        ),
    ]
