# Generated by Django 5.2.15 on 2026-07-03 08:01

from django.db import migrations, models


def backfill_created_at(apps, schema_editor):
    """既存の生徒には保護者アカウントの登録日を登録日時として補完する。"""
    Student = apps.get_model('booking', 'Student')
    for student in Student.objects.select_related('family__user'):
        joined = getattr(getattr(student.family, 'user', None), 'date_joined', None)
        if joined:
            student.created_at = joined
            student.save(update_fields=['created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0002_classroom'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.RunPython(backfill_created_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
